#include "codegen.h"
#include <stdexcept>

// ─── Helpers ─────────────────────────────────────────────────────────────────

std::string Codegen::newReg() {
    std::string r = "%r" + std::to_string(regCounter_++);
    declaredRegs_.push_back(r);
    return r;
}

std::string Codegen::varReg(const std::string& name) {
    if (!varToReg_.count(name))
        throw std::runtime_error("Codegen error: undeclared variable '" + name + "'");
    return varToReg_[name];
}

std::string Codegen::newLabel(const std::string& prefix) {
    return prefix + "_" + std::to_string(labelCounter_++);
}

void Codegen::emit(const std::string& instr) {
    out_ << "    " << instr << ";\n";
}

void Codegen::emitLabel(const std::string& lbl) {
    out_ << lbl << ":\n";
}

// ─── Top-level ────────────────────────────────────────────────────────────────

std::string Codegen::generate(const std::vector<StmtPtr>& program) {
    // First pass: collect all register declarations
    // (We buffer instructions, prepend .reg declarations at the end)
    out_.str(""); out_.clear();

    for (const auto& s : program) genStmt(*s);

    std::string instructions = out_.str();

    // Build final PTX module
    std::ostringstream final_out;
    final_out << "//\n";
    final_out << "// Generated by ToyCompiler -> PTX backend\n";
    final_out << "// Target: NVIDIA PTX Virtual ISA (sm_75 compatible)\n";
    final_out << "//\n\n";
    final_out << ".version 7.0\n";
    final_out << ".target sm_75\n";
    final_out << ".address_size 64\n\n";
    final_out << ".visible .func toy_main()\n";
    final_out << "{\n";

    // Emit .reg declarations (one per register used)
    if (!declaredRegs_.empty()) {
        final_out << "    // Register declarations (.s32 = 32-bit signed integer)\n";
        for (const auto& r : declaredRegs_)
            final_out << "    .reg .s32 " << r << ";\n";
        // Predicate registers for conditionals
        final_out << "    .reg .pred %p<" << labelCounter_ + 4 << ">;\n";
        final_out << "\n";
    }

    final_out << instructions;
    final_out << "    ret;\n";
    final_out << "}\n";

    return final_out.str();
}

// ─── Statement generation ────────────────────────────────────────────────────

void Codegen::genStmt(const StmtNode& s) {
    switch (s.kind) {

        case StmtKind::VarDecl: {
            std::string reg = newReg();
            varToReg_[s.varName] = reg;
            if (s.initExpr) {
                std::string src = genExpr(*s.initExpr);
                emit("mov.s32 " + reg + ", " + src);
            } else {
                // Default-initialise to 0
                emit("mov.s32 " + reg + ", 0");
            }
            out_ << "    // var '" << s.varName << "' -> " << reg << "\n";
            break;
        }

        case StmtKind::ExprStmt:
            genExpr(*s.expr);   // side-effects only (e.g. assignment)
            break;

        case StmtKind::Print: {
            // In real PTX you'd call a device-side printf via vprintf;
            // here we emit a clearly-labelled comment + the computed register
            // so the output documents the mechanism.
            std::string val = genExpr(*s.printExpr);
            out_ << "    // --- print(" << val << ") ---\n";
            // In a real CUDA kernel, the intrinsic is:
            //   call (retval), vprintf, (fmt_ptr, args_ptr);
            // We emit a placeholder that makes the intent explicit:
            emit("// vprintf(\"%%d\\n\", " + val + ")   // [runtime call placeholder]");
            break;
        }

        case StmtKind::If: {
            // Evaluate condition -> predicate register
            std::string condReg = genExpr(*s.condition);
            std::string predReg = "%p" + std::to_string(labelCounter_);
            std::string labelElse = newLabel("IF_ELSE");
            std::string labelEnd  = newLabel("IF_END");

            // setp.ne.s32 %p, condReg, 0   (true if condReg != 0)
            emit("setp.ne.s32 " + predReg + ", " + condReg + ", 0");

            if (s.elseBranch) {
                // @!p bra ELSE
                emit("@!" + predReg + " bra " + labelElse);
                genStmt(*s.thenBranch);
                emit("bra " + labelEnd);
                emitLabel(labelElse);
                genStmt(*s.elseBranch);
                emitLabel(labelEnd);
            } else {
                emit("@!" + predReg + " bra " + labelEnd);
                genStmt(*s.thenBranch);
                emitLabel(labelEnd);
            }
            break;
        }

        case StmtKind::While: {
            std::string labelTop  = newLabel("WHILE_TOP");
            std::string labelEnd  = newLabel("WHILE_END");
            std::string predReg   = "%p" + std::to_string(labelCounter_);

            emitLabel(labelTop);
            std::string condReg = genExpr(*s.whileCond);
            emit("setp.ne.s32 " + predReg + ", " + condReg + ", 0");
            emit("@!" + predReg + " bra " + labelEnd);
            genStmt(*s.whileBody);
            emit("bra " + labelTop);
            emitLabel(labelEnd);
            break;
        }

        case StmtKind::Block:
            for (const auto& child : s.stmts) genStmt(*child);
            break;
    }
}

// ─── Expression generation ───────────────────────────────────────────────────
// Returns the name of the PTX register holding the result.

std::string Codegen::genExpr(const ExprNode& e) {
    switch (e.kind) {

        case ExprKind::IntLiteral:
            // Immediate: return value as a string literal (PTX accepts immediates inline)
            return std::to_string(e.ival);

        case ExprKind::Variable:
            return varReg(e.name);

        case ExprKind::Assign: {
            std::string src = genExpr(*e.left);
            std::string dst = varReg(e.name);
            emit("mov.s32 " + dst + ", " + src);
            return dst;
        }

        case ExprKind::UnaryOp: {
            std::string operand = genExpr(*e.left);
            std::string dst     = newReg();
            if (e.op == "-") {
                emit("neg.s32 " + dst + ", " + operand);
            } else if (e.op == "!") {
                // !x = (x == 0) ? 1 : 0
                // setp.eq then selp
                std::string pred = "%p" + std::to_string(labelCounter_++);
                out_ << "    .reg .pred " << pred << ";\n";
                emit("setp.eq.s32 " + pred + ", " + operand + ", 0");
                emit("selp.s32 " + dst + ", 1, 0, " + pred);
            }
            return dst;
        }

        case ExprKind::BinaryOp: {
            // Short-circuit eval for && and ||
            if (e.op == "&&" || e.op == "||") {
                std::string left  = genExpr(*e.left);
                std::string right = genExpr(*e.right);
                std::string dst   = newReg();
                std::string pl    = "%p" + std::to_string(labelCounter_++);
                std::string pr    = "%p" + std::to_string(labelCounter_++);
                std::string pd    = "%p" + std::to_string(labelCounter_++);
                emit("setp.ne.s32 " + pl + ", " + left  + ", 0");
                emit("setp.ne.s32 " + pr + ", " + right + ", 0");
                if (e.op == "&&")
                    emit("and.pred " + pd + ", " + pl + ", " + pr);
                else
                    emit("or.pred  " + pd + ", " + pl + ", " + pr);
                emit("selp.s32 " + dst + ", 1, 0, " + pd);
                return dst;
            }

            std::string left  = genExpr(*e.left);
            std::string right = genExpr(*e.right);
            std::string dst   = newReg();

            // Arithmetic
            if (e.op == "+") { emit("add.s32 " + dst + ", " + left + ", " + right); return dst; }
            if (e.op == "-") { emit("sub.s32 " + dst + ", " + left + ", " + right); return dst; }
            if (e.op == "*") { emit("mul.lo.s32 " + dst + ", " + left + ", " + right); return dst; }
            if (e.op == "/") { emit("div.s32 " + dst + ", " + left + ", " + right); return dst; }
            if (e.op == "%") { emit("rem.s32 " + dst + ", " + left + ", " + right); return dst; }

            // Comparisons — emit setp + selp to materialise 0/1 into a register
            std::string pred = "%p" + std::to_string(labelCounter_++);
            std::string ptxCmp;
            if      (e.op == "==") ptxCmp = "setp.eq.s32";
            else if (e.op == "!=") ptxCmp = "setp.ne.s32";
            else if (e.op == "<")  ptxCmp = "setp.lt.s32";
            else if (e.op == "<=") ptxCmp = "setp.le.s32";
            else if (e.op == ">")  ptxCmp = "setp.gt.s32";
            else if (e.op == ">=") ptxCmp = "setp.ge.s32";
            else throw std::runtime_error("Unknown operator: " + e.op);

            emit(ptxCmp + " " + pred + ", " + left + ", " + right);
            emit("selp.s32 " + dst + ", 1, 0, " + pred);
            return dst;
        }
    }
    throw std::runtime_error("Unreachable in genExpr");
}